// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Zj49DcuWYmgjSpK76BQhaiwSjDIjhXo',
    appId: '1:490645908949:android:f6265f934d12af0942e15c',
    messagingSenderId: '490645908949',
    projectId: 'security-application-2b08d',
    storageBucket: 'security-application-2b08d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArFBzyzg11V3TTu-0lUZmUsYIx4S55kgQ',
    appId: '1:490645908949:ios:b49cd87b1576f02942e15c',
    messagingSenderId: '490645908949',
    projectId: 'security-application-2b08d',
    storageBucket: 'security-application-2b08d.appspot.com',
    iosBundleId: 'com.example.securityApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu0HDPla9pefGaVPeUMngIvoV6Z7Y-WPc',
    appId: '1:490645908949:web:0aa16ccff7a7f8ee42e15c',
    messagingSenderId: '490645908949',
    projectId: 'security-application-2b08d',
    authDomain: 'security-application-2b08d.firebaseapp.com',
    storageBucket: 'security-application-2b08d.appspot.com',
    measurementId: 'G-4ZE7X6PPVN',
  );
}
